public enum FormulaType {
    TRUE, NOTTRUE, FALSE, NOTFALSE, PROPOSITION, NOTPROPOSITION, AND, NOTAND, OR, NOTOR, CONDITION, NOTCONDITION, BICONDITION,
    NOTBICONDITION, NECESSARILY, NOTNECESSARILY, POSSIBLY, NOTPOSSIBLY
}
